### ISSUE TITLE
Help from Experienced Testing Developers

### ISSUE THREAD

**Issue by jnmclarty** [Equitable/trump#5]
The very small core team working on Trump has limited experience with advanced testing concepts.

Support with designing the testing framework; setting up the project to be able to create tests quickly, creating smart "SetUps" and "TearDowns" related to database applications like Trump, high-level organization/identification of testing classes, as well as enabling common/modern testing features would all be a big help...  

The team stands ready to embrace any and all forms of support in this area (or, actually, any area, but this area is a priority.).

We are hopeful, and actually rushing the 0.0.1 release, to be considered for adopt py.test

**Comment by jnmclarty** [comment]
Trump's template engine is expected to grow.  If the testing framework could respond to that dynamically, that would be so cool.  I imagine it's possible, looking through all of a certain module's classes, inspecting inheritance, would be a good place to start.

Also, SQLAlchemy testing individual SQLAlchemy objects, and the cases, is something I don't know how to tackle intelligently.

**Comment by jnmclarty** [comment]
Created some testing pseudo, for what I think Trump needs.  

https://github.com/Equitable/trump/blob/master/trump/tests/testingpseudo.py

...not exactly sure if it's ideal, or if it's practical/comprehensive.

**Comment by kissgyorgy** [comment]
Hi guys!

I'm one of your assigned helper for "Adopt pytest" campaign.
This might sound terribly childish, but I will only participate if you make the codeabase PEP8 compliant.
Please let me know if you want/can do this ASAP because we can be reassigned to a different project.

If you don't follow the simplest of best practices, you have bigger problems than testing.

Also I only want to spend my freetime on projects I enjoy, and an ugly coding style is not one of them, sorry :smile:

**Comment by jnmclarty** [comment]
Give me 12 hours.

It's not PEP8 compliant, but largely only because we're just getting out of a planning stage.   We would definitely support moving to PEP8 compliance.   FWIW, there's roughly 4K lines of code checked in (including doc building scripts), and I've never checked the PEP8 compliance.

While I take care of that, want to have a peak at the testing pseudo code linked above? Let me know if you have experience with that kind of stuff?  (SQLAlchemy? Database object testing? Support for multi-databases?)

**Comment by jnmclarty** [comment]
Oh, and thanks for volunteering.

**Comment by jnmclarty** [comment]
Created an issue to discuss further PEP 8, here: #12

**Comment by kissgyorgy** [comment]
It's trivial but I have to mention this: Testing is costly. If you write test during changing the coding style, you constantly have to rewrite the test also. This is also a reason I asked for this style change. 

In the ideal case, tests are written at the same time (preferably before) when the code itself, so you got instant feedback when you break something even with trivial changes like styling.

It's really an art to find the right balance between writing enough tests but not wasting too time for them.

**Comment by kissgyorgy** [comment]
> While I take care of that, want to have a peak at the testing pseudo code linked above?

Ok, there is [two way of organizing test code](http://pytest.org/latest/goodpractises.html#choosing-a-test-layout-import-rules). One is to put the tests next to the code, inside the package. It will be installed with the project. This one makes sense when you want to deploy the tests for every installation. It usually is not the case.

The other which I prefer is to put it outside the project package. I like this better, because this way you are forced to isolate the tests from the code, so you basically have to use it like you would from an external library. For this to work your pacakage need to be installed, but it's not a problem when you install it in editable mode `pip install -e project_root`.

**Comment by jnmclarty** [comment]
Is there a way to bridge the two approaches?  I think an internal one for templates, and an external one for the ORM, would be a smart delineation.  

I know how the basics of the first approach work, I've created extremly basic tests on two of my other projects, and tweaked tests when I contributed to pandas (a big/successful Open Source project).

I'm hoping for some clever testing approaches for the templates, that rely on the/a class naming convention (those t,f,m,s,v you asked about [but I'm open to changing])...to loop through and check all the template objects, and ensure that they work pythonically (ie, not have to shove each one into a database object, every time it's tested).  The only alternative I can think of, is adding in mixins, to be picked up solely for testing purposes.

The end users of Trump, is likely to write their own templates.  And, possibly many of them. 

By 2016, there could be 100s of templates.

**Comment by jnmclarty** [comment]
This project, could, in the future be easily pulled apart and delineated between the ORM and the Template.  Actually, I'm talking myself into doing that sooner rather than later.  The templates could have very tight release cycle, while the ORM should have only bugs/small tweaks.

The templates are all just pure python objects, that have specific naming, inheritance and constructor requirements.  Templates should be database agnostic.

I think the "inside package" approach is best for the template testing.
I think the "outside package" approach is best for the ORM testing.

Does what I'm saying make sense?

**Comment by kissgyorgy** [comment]
> If the testing framework could respond to that dynamically, that would be so cool.

The whole philosophy os testing is that you validate your code and think about it one more time beside writing the right code. This is the reason that test code usually exceeds the amount of production code itself. So, tests should all manually written. Whenever I learned about testing best practices, they always said that tests should be readable, simple as much as possible so it's _easily understandable._ Usually it's not a good idea to dynamically test a bunch of different classes.

There are two types of testing I know of which makes it possible some kind of dynamism; one is parametrized testing, where you give a bunch of different parameters to the same test method. It is used where you have a very large number of edge cases and all kinds of different data you need to test.

The other is [equivalence class testing](http://en.wikipedia.org/wiki/Equivalence_partitioning). It is used to group values and test according these types of values.

> Also, SQLAlchemy testing individual SQLAlchemy objects, and the cases, is something I don't know how to tackle intelligently.

There are two ways that I can think of; you can write testable code. It's argued a lot and is a very complicated topic and there is a disagreement amongst very good programmers. The other is to mock complicated objects for tests. Pyramid web framework does the first, I think it's much simpler to do, and your code is more easy to understand this way, less rigid, more flexible. However pytest makes it really easy to mock out complicated components.

> Created some testing pseudo, for what I think Trump needs.

I usually like the approach "Just do it." instead of planning :smile: 
I will review your plan later.

> I'm hoping for some clever testing approaches for the templates, that rely on the/a class naming convention (those t,f,m,s,v you asked about [but I'm open to changing]).

I think this is not a good idea, see for explanation above.

> The only alternative I can think of, is adding in mixins, to be picked up solely for testing purposes.

Test helpers should go into tests in form of mocks, helpers, etc. The only case you would write these in the code itself, where it's not possible to separate them. E.g. [Flask app has a test_client method](https://github.com/mitsuhiko/flask/blob/master/flask/app.py#L829) 

> The end users of Trump, is likely to write their own templates. And, possibly many of them.

Then those templates also needs to be tested and those tests should written manually. Another really good byproduct (maybe feature?) of tests if that a newcomer look at the test code, thy can instantly see who is the library supposed to be used! In case of complicated dynamic test, that would be not possible. Also your tests have to have absolutely no mistakes. There is more room for them in case of complicated 
test code.

Your last comment makes total sense and this kind of test separation sounds like a pretty good idea! :+1:

**Comment by jnmclarty** [comment]
Ok, I'm on board with all that, ready to embrace your recommendations.

:+1: :+1: :+1:

**Comment by jnmclarty** [comment]
@kissgyorgy Question: I had to hack a [.travis.yml file](https://github.com/Equitable/trump/blob/master/.travis.yml#L14), to get the coverage to work properly.  The hack is needed cause Trump comes with config files that get created during setup.py.  But, the weird thing was, I needed to add the `PYTHONPATH=`pwd`` part, even when I was running py.test from the command line in my repo folder on my linux box, otherwise I got import errors.  I'm thinking I'm doing something wrong, with the project's setup, but I don't know what.

**Comment by jnmclarty** [comment]
...shouldn't it be possible to run the test suite on a freshly cloned (ie, not-installed?) copy of Trump? from the repo folder?  Can I flag tests that require the config file, and skip thoses tests if the module isn't "intstalled"?

I'm developing on linux.

**Comment by jnmclarty** [comment]
@kissgyorgy Question 2: Why does Trump work with Travis on my personal fork, but not the main project? https://travis-ci.org/jnmclarty/trump vs https://travis-ci.org/Equitable/trump

**Comment by kissgyorgy** [comment]
The simplest way to make testing possible if you install the package, and you can import it from the tests.
You need relative import from inside package tests.

`pip install -e .` where setup.py is, and your package is installed. As simple as that.

You just overcomplicate things with your personal fork. I suggest to delete that and push to this repository to a different branch.

**Comment by jnmclarty** [comment]
Thanks! That makes more sense, it all works now.  Trump is weighing in at a whopping 15% (ha!) [coverage](https://coveralls.io/r/Equitable/trump), as reported by coveralls.io after the most recent Travis build.

My goal is: 70% coverage, on a SQLlite file, and PostGres 9.4, within a week. 

I need an intelligent mechanism to "switch", the tests I write, between two database back-ends.  Thoughts?  I don't need to always run both, but before a release, I would.  py.test arguments? config file of some kind?  will google tomorrow...

**Comment by tgmiller5** [comment]
The following link does not work: https://github.com/Equitable/trump/blob/master/trump/tests/testingpseudo.py

**Comment by jnmclarty** [comment]
@tgmiller5 Thanks, and apologies, it started out as *.py file, but, it's really just a bunch of python-comments: 

https://github.com/Equitable/trump/blob/master/trump/tests/testingpseudo

**Comment by jnmclarty** [comment]
Lots of this is getting stale
